spring:
  datasource:
    schema: classpath:db.sql
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: root



mybatis:
  config-location: classpath:mybatis/mybatis-config.xml