spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/workflow?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
